In [38]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import Encoder as enc

oe = OrdinalEncoder()
ohe = OneHotEncoder()
le = LabelEncoder()

imputer = SimpleImputer(missing_values = pd.NA, strategy = 'mean')

train_csv = pd.read_csv('tit_train.csv')
X = train_csv.drop(columns = ['PassengerId','Ticket','Cabin','Embarked','Survived'])
#X['Name'] = le.fit_transform(X['Name'])
#X['Sex'] = le.fit_transform(X['Sex'])
X['Name'] = enc.ArrayEncoder(X['Name'])
X['Sex'] = le.fit_transform(X['Sex'])
X = imputer.fit_transform(X)

y = train_csv['Survived']

test_csv = pd.read_csv('tit_test.csv')
tX = test_csv.drop(columns = ['PassengerId','Ticket','Cabin','Embarked'])
#tX['Name'] = le.fit_transform(tX['Name'])
#tX['Sex'] = le.fit_transform(tX['Sex'])
tX['Name'] = enc.ArrayEncoder(tX['Name'])
tX['Sex'] = le.fit_transform(tX['Sex'])
tX = imputer.fit_transform(tX)
#test_y = test_csv['Survived']

In [39]:
#train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2) 
train_X = X
train_y = y
test_X = tX

In [40]:
scaler = StandardScaler()
train_X = scaler.fit_transform(train_X)
test_X = scaler.transform(test_X)

In [41]:
test_X

array([[ 0.82737724, -0.03352008,  0.73769513, ..., -0.4745452 ,
        -0.47367361, -0.49078316],
       [ 0.82737724, -0.03352008, -1.35557354, ...,  0.43279337,
        -0.47367361, -0.50747884],
       [-0.36936484, -0.03352008,  0.73769513, ..., -0.4745452 ,
        -0.47367361, -0.45336687],
       ...,
       [ 0.82737724, -0.03352008,  0.73769513, ..., -0.4745452 ,
        -0.47367361, -0.50244517],
       [ 0.82737724, -0.03352008,  0.73769513, ..., -0.4745452 ,
        -0.47367361, -0.48633742],
       [ 0.82737724, -0.03352008,  0.73769513, ...,  0.43279337,
         0.76762988, -0.19824428]])

In [42]:
clf = MLPClassifier(max_iter=5000).fit(train_X, train_y)

In [43]:
#Passenger Class, Name, Sex(m=1,f=0), Age, Siblings/Spouse, Parents/Children, Fare
inputArray = scaler.transform(np.array([1, enc.StringEncoder('Eden, Chaz'), 1, 17, 3, 2, 8]).reshape(1,-1))
clf.predict(inputArray)

array([1], dtype=int64)

In [44]:
clf.predict(test_X[:400])

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,