In [69]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

ohe = OneHotEncoder()
le = LabelEncoder()

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

train_csv = pd.read_csv('tit_train.csv')
X = train_csv.drop(columns = ['Ticket','Cabin','Embarked','Survived'])
X['Name'] = le.fit_transform(X['Name'])
X['Sex'] = le.fit_transform(X['Sex'])
X = imputer.fit_transform(X)

y = train_csv['Survived']

test_csv = pd.read_csv('tit_test.csv')
tX = test_csv.drop(columns = ['Ticket','Cabin','Embarked'])
tX['Name'] = le.fit_transform(tX['Name'])
tX['Sex'] = le.fit_transform(tX['Sex'])
tX = imputer.fit_transform(tX)
#test_y = test_csv['Survived']

In [70]:
#train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.2) 
train_X = X
train_y = y
test_X = tX

In [71]:
scaler = StandardScaler()
train_X = scaler.fit_transform(train_X)
test_X = scaler.transform(test_X)

In [82]:
test_X

array([[ 1.73399584,  0.82737724, -0.92920405, ..., -0.4745452 ,
        -0.47367361, -0.49078316],
       [ 1.73788372,  0.82737724, -0.16329109, ...,  0.43279337,
        -0.47367361, -0.50747884],
       [ 1.74177161, -0.36936484, -0.68426742, ..., -0.4745452 ,
        -0.47367361, -0.45336687],
       ...,
       [ 3.34746731,  0.82737724, -0.43933078, ..., -0.4745452 ,
        -0.47367361, -0.50244517],
       [ 3.35135519,  0.82737724, -0.23716087, ..., -0.4745452 ,
        -0.47367361, -0.48633742],
       [ 3.35524307,  0.82737724, -0.55596728, ...,  0.43279337,
         0.76762988, -0.19824428]])

In [77]:
clf = MLPClassifier(max_iter=5000).fit(train_X, train_y)

In [89]:
test_X[45]

array([ 1.90895058,  0.82737724, -0.56374304,  0.73769513, -0.36161755,
       -0.4745452 , -0.47367361, -0.48885426])

In [90]:
clf.predict(test_X[:800])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,